### ISSUE TITLE
Port issues

### ISSUE THREAD

**Issue by wi-ski** [heroku/heroku-buildpack-google-chrome#13]
Having issues:

```
2017-05-09T16:43:16.127206+00:00 app[web.1]: WARN: { Error: spawn google-chrome-stable --remote-debugging-port=19409 ENOENT
2017-05-09T16:43:16.127212+00:00 app[web.1]:     at exports._errnoException (util.js:1050:11)
2017-05-09T16:43:16.127215+00:00 app[web.1]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
2017-05-09T16:43:16.127216+00:00 app[web.1]:     at onErrorNT (internal/child_process.js:367:16)
2017-05-09T16:43:16.127217+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2017-05-09T16:43:16.127217+00:00 app[web.1]:     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
2017-05-09T16:43:16.127218+00:00 app[web.1]:     at Module.runMain (module.js:607:11)
2017-05-09T16:43:16.127219+00:00 app[web.1]:     at run (bootstrap_node.js:423:7)
2017-05-09T16:43:16.127220+00:00 app[web.1]:     at startup (bootstrap_node.js:147:9)
2017-05-09T16:43:16.127221+00:00 app[web.1]:     at bootstrap_node.js:538:3
2017-05-09T16:43:16.127221+00:00 app[web.1]:   code: 'ENOENT',
2017-05-09T16:43:16.127222+00:00 app[web.1]:   errno: 'ENOENT',
2017-05-09T16:43:16.127222+00:00 app[web.1]:   syscall: 'spawn google-chrome-stable --remote-debugging-port=19409',
2017-05-09T16:43:16.127223+00:00 app[web.1]:   path: 'google-chrome-stable --remote-debugging-port=19409',
2017-05-09T16:43:16.127223+00:00 app[web.1]:   spawnargs: [ '--remote-debugging-port=9222', '' ] }
```

Things I dont get:

a. Don't we get assigned a port when using any given Dyno? Meaning - having this buildpack default to port 9222 is kinda inconvenient?  I would love to be educated on this :(

b. Im using the build pack and it cant find the binary :( How fix?

**Comment by wi-ski** [comment]
Heres it doing it with the regular `google-chrome` command:

```
2017-05-09T16:41:54.531533+00:00 app[web.1]: WARN: { Error: spawn google-chrome --remote-debugging-port=19409 ENOENT
2017-05-09T16:41:54.531546+00:00 app[web.1]:     at exports._errnoException (util.js:1050:11)
2017-05-09T16:41:54.531547+00:00 app[web.1]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
2017-05-09T16:41:54.531547+00:00 app[web.1]:     at onErrorNT (internal/child_process.js:367:16)
2017-05-09T16:41:54.531548+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2017-05-09T16:41:54.531549+00:00 app[web.1]:     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
2017-05-09T16:41:54.531550+00:00 app[web.1]:     at Module.runMain (module.js:607:11)
2017-05-09T16:41:54.531551+00:00 app[web.1]:     at run (bootstrap_node.js:423:7)
2017-05-09T16:41:54.531551+00:00 app[web.1]:     at startup (bootstrap_node.js:147:9)
2017-05-09T16:41:54.531552+00:00 app[web.1]:     at bootstrap_node.js:538:3
2017-05-09T16:41:54.531553+00:00 app[web.1]:   code: 'ENOENT',
2017-05-09T16:41:54.531554+00:00 app[web.1]:   errno: 'ENOENT',
2017-05-09T16:41:54.531554+00:00 app[web.1]:   syscall: 'spawn google-chrome --remote-debugging-port=19409',
2017-05-09T16:41:54.531555+00:00 app[web.1]:   path: 'google-chrome --remote-debugging-port=19409',
2017-05-09T16:41:54.531556+00:00 app[web.1]:   spawnargs: [ '--remote-debugging-port=9222', '' ] }
```

**Comment by wi-ski** [comment]
Ultimately - it would be awesome to just understand how ports work here :(

**Comment by joshwlewis** [comment]
Hi @wi-ski,

> Don't we get assigned a port when using any given Dyno? Meaning - having this buildpack default to port 9222 is kinda inconvenient?

Heroku web dynos do get a random $PORT assigned. However, that's designed to hook up to a webserver of some kind. The reason we are specifying `--remote-debugger-port` here is just to prevent Chrome from exiting immediately, not to wire up anything. I don't have a great concept of the use case for `--remote-debugging-port` outside of preventing immediate Chrome exits. Are you trying to use the `--remote-debugging-port` for something besides that?

> Im using the build pack and it cant find the binary :( How fix?

It should be on your `$PATH` already. If it's chromedriver that can't find Chrome, there's a section about that at the bottom of the README.
