### ISSUE TITLE
Chrome failed to start: crashed

### ISSUE THREAD

**Issue by rslifka** [heroku/heroku-buildpack-google-chrome#17]
Excited to see this supported on Heroku! Running with Ruby only (no Rails), exits straight away upon starting. Happy to work with you to help debug, just let me know! 😄 

## Stack Trace
```
[SeleniumRummer] Chrome options => {:chromeOptions=>{:args=>["--ignore-certificate-errors"], :binary=>"/app/.apt/opt/google/chrome/chrome"}}
[SeleniumRunner] Starting driver
rake aborted!
Selenium::WebDriver::Error::UnknownError: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 3.13.0-112-generic x86_64)
/app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
/app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
/app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
/app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
/app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
/app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/bridge.rb:678:in `raw_execute'
/app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/bridge.rb:110:in `create_session'
/app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/bridge.rb:73:in `initialize'
/app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/chrome/bridge.rb:52:in `initialize'
/app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/common/driver.rb:61:in `new'
/app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/common/driver.rb:61:in `for'
/app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver.rb:88:in `for'...
```

## Buildpacks

```
1. https://github.com/heroku/heroku-buildpack-chromedriver
2. https://github.com/heroku/heroku-buildpack-google-chrome
3. heroku/ruby
```

**Comment by rslifka** [comment]
Ah, I see that you can specify the `GOOGLE_CHROME_CHANNEL` to `beta` which is where the `--headless` option resides currently. Checking to see if that works.

**Comment by rslifka** [comment]
Redeploy with `beta` still no bueno:

```
[SeleniumRummer] Chrome options => {:chromeOptions=>{:args=>["--ignore-certificate-errors"], :binary=>"/app/.apt/opt/google/chrome-beta/chrome"}}
[SeleniumRunner] Starting driver
rake aborted!
Selenium::WebDriver::Error::UnknownError: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 3.13.0-112-generic x86_64)
/app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
```

You can see it's picked up the beta launcher in the opts path above.

**Comment by rslifka** [comment]
How does `chromedriver` related to `chrome`? I noticed here that the latest version ([2.29](https://chromedriver.storage.googleapis.com/index.html?path=2.29/)) was released two weeks prior to the beta of Chrome.

Notice the bit about adding support for Chrome up through 58 (we need 59).

```
----------ChromeDriver v2.29 (2017-04-04)----------
Supports Chrome v56-58
Resolved issue 1521: Assignment to Object.prototype.$family causes a crash [['Pri-1']]
Resolved issue 1482: Chromedriver cannot handle the alert generated by onbeforeunload event [['OS-All', 'Pri-2']]
Resolved issue 1315: |switch_to.window| does not visually switch tabs [['OS-All', 'Pri-3']]
```

**Comment by rslifka** [comment]
Interestingly, locally on macOS using the latest version of chromedriver, it works.

```
$ chromedriver --version
ChromeDriver 2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b)
```

That being said, I'm entirely open to the possibility this isn't the case across platforms 😄

**Comment by rslifka** [comment]
I attempted to use the forked version of this buildpack at v59 (https://github.com/heroku/heroku-buildpack-google-chrome/pull/16) but still no dice.

**Comment by rslifka** [comment]
After doing a bit of research, it does appear that headless support will have to wait for both v59 and an update of Chromedriver after the current 2.29. Presumably once v59 is released, another build of Chromedriver will ride sidecar. Is that a correct assumption? Or should it be able to work as-is? (I'm confused - some people talk about `--headless` support in v58 which I can't find corroboration for)

**Comment by rslifka** [comment]
Yep, v59 confirmed. Not sure how folks are using this pre-59 :)

https://developers.google.com/web/updates/2017/04/headless-chrome

If this issue persists after v59 and associated Chromedriver are released, I'll re-open it.
