### ISSUE TITLE
"exited abnormally"

### ISSUE THREAD

**Issue by winou75** [heroku/heroku-buildpack-google-chrome#20]
Hi, I've tried many times with Watir/Capybara, but constantly getting this error ...

my code: 

```Capybara.register_driver :chrome do |app|
  Capybara::Selenium::Driver.new(
     app,
     browser: :chrome,
     desired_capabilities: Selenium::WebDriver::Remote::Capabilities.chrome(
     	'chromeOptions' => {
    	'binary' => "/app/.apt/usr/bin/google-chrome",
	      'args' => [
	      	"--headless"
	      ]
	    }
     )
  )
end

Capybara.configure do |config|
  config.run_server = false
  config.default_driver = :chrome
  config.app_host = 'https://www.google.com' # change url
end

browser = Capybara.current_session
browser.visit "https://www.google.com"
```

the response:

``` Selenium::WebDriver::Error::UnknownError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 3.13.0-112-generic x86_64)
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/bridge.rb:678:in `raw_execute'
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/bridge.rb:110:in `create_session'
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/bridge.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/chrome/bridge.rb:52:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/common/driver.rb:61:in `new'
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/common/driver.rb:61:in `for'
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver.rb:88:in `for'
	from /app/vendor/bundle/ruby/2.3.0/gems/capybara-2.14.0/lib/capybara/selenium/driver.rb:22:in `browser'
	from /app/vendor/bundle/ruby/2.3.0/gems/capybara-2.14.0/lib/capybara/selenium/driver.rb:62:in `visit'
	from /app/vendor/bundle/ruby/2.3.0/gems/capybara-2.14.0/lib/capybara/session.rb:269:in `visit'
	from (irb):55
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/console.rb:110:in `start'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/console.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'```

**Comment by simzen85** [comment]
@winou75 use this fork https://github.com/kevinsawicki/heroku-buildpack-xvfb-google-chrome/ , it works for me while the official Heroku buildpack doesn't

**Comment by edmorley** [comment]
Hi @winou75 did you get this figured out in the end? :-)

**Comment by edmorley** [comment]
Closing this out for inactivity. If the issue is still occurring let us know and we can reopen :-)
